### ISSUE TITLE
File Visibility Differs Between command and script

### ISSUE THREAD

**Issue by jmwright** [stemn/stemn-pipeline-containers#1]
I set up a pipeline using a third-party image [here](https://stemn.com/files/5b15410c252c9400192ab940/5b19f2c1b2698100194c80cf?revision=5b1a0137b2698100194c827f).

If I run `asciidoctor-pdf` as a command, it throws an error that the file isn't accessible. I can confirm that I get a blank directory listing with `ls` if I run it as a command. However, if I run `asciidoctor-pdf` or `ls` as a script, the files are visible and everything works as expected.

What's the difference between running something as a command vs a script? Are they supposed to have different file visibility?

**Comment by sabrehagen** [comment]
When a `script` is supplied the container's [`WORKDIR`](https://docs.docker.com/engine/reference/builder/#workdir) is set to `/pipeline`. It is not set when `script` is not supplied. In our experience this caused some containers to break due to the container's `CMD` expecting a different working directory.
