### ISSUE TITLE
Pipeline Stage Hung On Upload

### ISSUE THREAD

**Issue by jmwright** [stemn/stemn-pipeline-containers#3]
I've got two pipelines hung on the upload stage.

https://stemn.com/project/5b15410c252c9400192ab940/pipelines

It could be because the file was never generated per #2 .

**Comment by sabrehagen** [comment]
The bug you encountered previously with upload is not fixed fully it seems. It resolved itself for your previous pipeline when I made a code change, but is back again.  I will try working with your files to have another shot.

In the meantime, I notice some of the cadquery containers are running in interactive mode again. Unfortunately due to some difference between development and production, these logs are not being sent to the front end in real time, so you are not seeing them.

```
pipeline-server% docker logs 5b217c4778761f00199167e1-stage_0-step_1
INFO: Reading from file './robot_assembly.py'
INFO: Parsed Script './robot_assembly.py'.
INFO: This script provides no customizable build parameters.
INFO: The script will run with default variable values
INFO: use --param_file to provide a json file that contains values to override the defaults
No handlers could be found for logger "cqparts.assembly"
<Chassis: height=25.0, length=140.0, width=75.0>
host temp folder: /tmp/tmpnkJ3br/html
serving: http://0.0.0.0:9041/
opening in browser: http://0.0.0.0:9041/
press [ctrl+c] to stop server
```

**Comment by jmwright** [comment]
There are probably 20 or 25 pipelines still running from my work earlier today. I'm not sure what effect that's having on your server load. I haven't edited that pipeline in the last 7 days according to the front end, and it ran successfully a couple of days ago. It doesn't seem like I've changed anything, so I don't know why it's running differently.

**Comment by jmwright** [comment]
Ok, I figured out what was causing the build command to go into server mode. If the script that's being processed isn't CQGI (CadQuery Gateway Interface) compliant, the script will default to server mode. My thought is that it should error and quit instead. In any case, it's an issue with the CadQuery command.

It would still be nice to have a timeout on pipelines or the ability to kill one though.
